### ISSUE TITLE
Do not assume white as the default console color

### ISSUE THREAD

**Issue by lmakarov** [hechoendrupal/drupal-console-launcher#103]
The launcher assumes white as the default console color.
Not only this may not be the case, but also colors may not match in different terminals.

Here's what I get when running `drupal --version`:

![image](https://cloud.githubusercontent.com/assets/1205005/26475845/0ea05fd0-416f-11e7-9984-c050885c22f9.png)

As you can see the color is changed to light-grey-bold in my case.

**Comment by jmolivas** [comment]
PR #104  Merged
