### ISSUE TITLE
Something is wrong with your drupal.phar archive

### ISSUE THREAD

**Issue by TMardi** [hechoendrupal/drupal-console-launcher#148]
Hello my friends, I keep getting the error:

> Something is wrong with your drupal.phar archive.
 Try downloading again by executing from your terminal:
 curl https://drupalconsole.com/installer -L -o drupal.phar

I have followed the following instructions while in my Drupal root folder:

curl https://drupalconsole.com/installer -L -o drupal.phar
mv drupal.phar /usr/local/bin/drupal
chmod +x /usr/local/bin/drupal

After these steps I type in 'drupal self-update' or 'drupal' in my terminal but keep getting the error message. Am I doing something wrong? I am on WSL.

Thanks

**Comment by jmolivas** [comment]
@TMardi could you try this to test your downloaded file:
```
curl https://drupalconsole.com/installer -L -o drupal.phar
php drupal.phar 
```

**Comment by jmolivas** [comment]
Closing this one. Feel free to re-open if still happening after updating to the latest version.
