### ISSUE TITLE
getting back 500 error when trying to pull the drupal.phar file

### ISSUE THREAD

**Issue by philbert440** [hechoendrupal/drupal-console-launcher#171]

**Comment by komlenic** [comment]
The site is broken - if/until someone fixes it, you can download the .phar file here:
https://github.com/hechoendrupal/drupal-console-launcher/releases/tag/1.9.4

Or use the following to install Drupal Console Launcher:

```bash
curl https://github.com/hechoendrupal/drupal-console-launcher/releases/download/1.9.4/drupal.phar -L -o drupal.phar
mv drupal.phar /usr/local/bin/drupal
chmod +x /usr/local/bin/drupal
```
