### ISSUE TITLE
Launcher shows confusing "Could not find Drupal in the current path." Error message when command is run. 

### ISSUE THREAD

**Issue by carsonblack** [hechoendrupal/drupal-console-launcher#92]
After updating to rc17 the Launcher drupal command returns the message, "Could not find Drupal in the current path.". This should be changed to something that instructs the user to run the command within a Drupal project and reminds them of the documentation page fro the Launcher where we will explain what it is and why you are using it.

**Comment by jmolivas** [comment]
PR https://github.com/hechoendrupal/drupal-console-launcher/pull/93 merged .
